// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_alarmScreen_screen_init(void)
{
    ui_alarmScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_alarmScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_alarmScreen, &ui_img_ui_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_alarmScreen);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 360);
    lv_obj_set_height(ui_Container19, 360);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container19, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 11);
    lv_obj_set_y(ui_Label29, -138);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "闹钟界面");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmContainer = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_alarmContainer);
    lv_obj_set_width(ui_alarmContainer, 360);
    lv_obj_set_height(ui_alarmContainer, 150);
    lv_obj_set_align(ui_alarmContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_alarmContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_alarmContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_alarmContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_alarmButton = lv_btn_create(ui_alarmContainer);
    lv_obj_set_width(ui_alarmButton, 360);
    lv_obj_set_height(ui_alarmButton, 50);
    lv_obj_set_align(ui_alarmButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_alarmButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_alarmButton, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_alarmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alarmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmLabel = lv_label_create(ui_alarmButton);
    lv_obj_set_width(ui_alarmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarmLabel, "9:00");
    lv_obj_set_style_text_color(ui_alarmLabel, lv_color_hex(0x070606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmSwitch = lv_switch_create(ui_alarmButton);
    lv_obj_set_width(ui_alarmSwitch, 75);
    lv_obj_set_height(ui_alarmSwitch, 40);
    lv_obj_set_align(ui_alarmSwitch, LV_ALIGN_CENTER);


    ui_Container20 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 360);
    lv_obj_set_height(ui_Container20, 97);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 80);
    lv_obj_set_x(ui_Button7, -1);
    lv_obj_set_y(ui_Button7, 105);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "+");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Container20);
    lv_obj_set_width(ui_Button6, 80);
    lv_obj_set_height(ui_Button6, 80);
    lv_obj_set_x(ui_Button6, -1);
    lv_obj_set_y(ui_Button6, 105);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "-");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_alarmSwitch, ui_event_alarmSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmButton, ui_event_alarmButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmScreen, ui_event_alarmScreen, LV_EVENT_ALL, NULL);

}
