// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_calendar_screen_init(void)
{
    ui_calendar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_calendar, &ui_img_ui_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_calendar);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 360);
    lv_obj_set_height(ui_Container8, 360);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "日历");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar2 = lv_calendar_create(ui_Container8);
    lv_calendar_set_today_date(ui_Calendar2, 2025, 1, 1);
    lv_calendar_set_showed_date(ui_Calendar2, 2025, 1);
    lv_obj_t * ui_Calendar2_header = lv_calendar_header_arrow_create(ui_Calendar2);
    lv_obj_set_width(ui_Calendar2, 240);
    lv_obj_set_height(ui_Calendar2, 240);
    lv_obj_set_align(ui_Calendar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calendar2, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_radius(ui_Calendar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Calendar2, lv_color_hex(0xF4E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Calendar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Calendar2, ui_event_Calendar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calendar, ui_event_calendar, LV_EVENT_ALL, NULL);

}
