// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_home, &ui_img_ui_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepArc = lv_arc_create(ui_home);
    lv_obj_set_width(ui_stepArc, 360);
    lv_obj_set_height(ui_stepArc, 360);
    lv_obj_set_x(ui_stepArc, 0);
    lv_obj_set_y(ui_stepArc, -2);
    lv_obj_set_align(ui_stepArc, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_stepArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_stepArc, 0, 10000);
    lv_arc_set_value(ui_stepArc, 0);
    lv_arc_set_bg_angles(ui_stepArc, 0, 40);
    lv_arc_set_rotation(ui_stepArc, 70);
    lv_obj_set_style_arc_color(ui_stepArc, lv_color_hex(0xB3B0B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_stepArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_stepArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_stepArc, lv_color_hex(0xF91512), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_stepArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_stepArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_stepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_stepImage = lv_img_create(ui_stepArc);
    lv_img_set_src(ui_stepImage, &ui_img_footsteps_png);
    lv_obj_set_width(ui_stepImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stepImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stepImage, -30);
    lv_obj_set_y(ui_stepImage, -20);
    lv_obj_set_align(ui_stepImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_stepImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stepImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_steplabel = lv_label_create(ui_stepArc);
    lv_obj_set_width(ui_steplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_steplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_steplabel, 15);
    lv_obj_set_y(ui_steplabel, -20);
    lv_obj_set_align(ui_steplabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_steplabel, "0");

    ui_batArc = lv_arc_create(ui_home);
    lv_obj_set_width(ui_batArc, 360);
    lv_obj_set_height(ui_batArc, 360);
    lv_obj_set_x(ui_batArc, 0);
    lv_obj_set_y(ui_batArc, 2);
    lv_obj_set_align(ui_batArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_batArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_batArc, 0);
    lv_arc_set_bg_angles(ui_batArc, 0, 40);
    lv_arc_set_rotation(ui_batArc, 250);
    lv_obj_set_style_arc_color(ui_batArc, lv_color_hex(0xB3B0B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batArc, lv_color_hex(0x1296DB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_batArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_batArc);
    lv_img_set_src(ui_Image4, &ui_img_battery_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -30);
    lv_obj_set_y(ui_Image4, 10);
    lv_obj_set_align(ui_Image4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batlabel = lv_label_create(ui_batArc);
    lv_obj_set_width(ui_batlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batlabel, 15);
    lv_obj_set_y(ui_batlabel, 20);
    lv_obj_set_align(ui_batlabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_batlabel, "100%");

    ui_Container3 = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 260);
    lv_obj_set_height(ui_Container3, 235);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labeltime = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Labeltime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeltime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeltime, 0);
    lv_obj_set_y(ui_Labeltime, -90);
    lv_obj_set_align(ui_Labeltime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeltime, "10:30");
    lv_obj_set_style_text_letter_space(ui_Labeltime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Labeltime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeltime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Labeltime, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -10);
    lv_obj_set_y(ui_Label5, -50);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "2025年12月12日");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}
