// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_timesetting_screen_init(void)
{
    ui_timesetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_timesetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_timesetting, &ui_img_ui_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_timesetting);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 360);
    lv_obj_set_height(ui_Container6, 360);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 10);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "时间设置");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 360);
    lv_obj_set_height(ui_Container10, 57);
    lv_obj_set_x(ui_Container10, -2);
    lv_obj_set_y(ui_Container10, -96);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourlabel = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_hourlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hourlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hourlabel, -1);
    lv_obj_set_y(ui_hourlabel, 4);
    lv_obj_set_align(ui_hourlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hourlabel, "15");
    lv_obj_set_style_text_font(ui_hourlabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, ":");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minuteslabel = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_minuteslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minuteslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minuteslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minuteslabel, "15");
    lv_obj_set_style_text_font(ui_minuteslabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minuteslabel, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_side(ui_minuteslabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label18 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, ":");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondslabel = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_secondslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_secondslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondslabel, "15");
    lv_obj_set_style_text_font(ui_secondslabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 360);
    lv_obj_set_height(ui_Container5, 106);
    lv_obj_set_x(ui_Container5, 7);
    lv_obj_set_y(ui_Container5, 88);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour = lv_roller_create(ui_Container5);
    lv_roller_set_options(ui_hour, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_hour, 15, LV_ANIM_OFF);
    lv_obj_set_width(ui_hour, 75);
    lv_obj_set_height(ui_hour, 100);
    lv_obj_set_x(ui_hour, -91);
    lv_obj_set_y(ui_hour, 35);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_hour, lv_color_hex(0x4FABF7), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hour, lv_color_hex(0x005295), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hour, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "\n:");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minutes = lv_roller_create(ui_Container5);
    lv_roller_set_options(ui_minutes,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_minutes, 15, LV_ANIM_OFF);
    lv_obj_set_width(ui_minutes, 75);
    lv_obj_set_height(ui_minutes, 100);
    lv_obj_set_x(ui_minutes, -91);
    lv_obj_set_y(ui_minutes, 35);
    lv_obj_set_align(ui_minutes, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_minutes, lv_color_hex(0x4FABF7), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minutes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_minutes, lv_color_hex(0x005295), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_minutes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minutes, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "\n:");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seconds = lv_roller_create(ui_Container5);
    lv_roller_set_options(ui_seconds,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_seconds, 15, LV_ANIM_OFF);
    lv_obj_set_width(ui_seconds, 75);
    lv_obj_set_height(ui_seconds, 100);
    lv_obj_set_x(ui_seconds, -91);
    lv_obj_set_y(ui_seconds, 35);
    lv_obj_set_align(ui_seconds, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_seconds, lv_color_hex(0x4FABF7), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_seconds, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_seconds, lv_color_hex(0x005295), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_seconds, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_seconds, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 360);
    lv_obj_set_height(ui_Container9, 84);
    lv_obj_set_x(ui_Container9, 2);
    lv_obj_set_y(ui_Container9, 146);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "确认");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_hour, ui_event_hour, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minutes, ui_event_minutes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seconds, ui_event_seconds, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timesetting, ui_event_timesetting, LV_EVENT_ALL, NULL);

}
