// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t * e);
lv_obj_t * ui_home;
lv_obj_t * ui_stepArc;
lv_obj_t * ui_stepImage;
lv_obj_t * ui_steplabel;
lv_obj_t * ui_batArc;
lv_obj_t * ui_Image4;
lv_obj_t * ui_batlabel;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Labeltime;
lv_obj_t * ui_Label5;
// CUSTOM VARIABLES


// SCREEN: ui_menu
void ui_menu_screen_init(void);
void ui_event_menu(lv_event_t * e);
lv_obj_t * ui_menu;
lv_obj_t * ui_Container7;
void ui_event_wifiButton(lv_event_t * e);
lv_obj_t * ui_wifiButton;
void ui_event_musicButton(lv_event_t * e);
lv_obj_t * ui_musicButton;
void ui_event_settingButton(lv_event_t * e);
lv_obj_t * ui_settingButton;
void ui_event_calendarButton(lv_event_t * e);
lv_obj_t * ui_calendarButton;
// CUSTOM VARIABLES


// SCREEN: ui_wifi
void ui_wifi_screen_init(void);
void ui_event_wifi(lv_event_t * e);
lv_obj_t * ui_wifi;
lv_obj_t * ui_Container1;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label10;
void ui_event_homeButton(lv_event_t * e);
lv_obj_t * ui_homeButton;
// CUSTOM VARIABLES


// SCREEN: ui_wificfg
void ui_wificfg_screen_init(void);
void ui_event_wificfg(lv_event_t * e);
lv_obj_t * ui_wificfg;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
// CUSTOM VARIABLES


// SCREEN: ui_musiclist
void ui_musiclist_screen_init(void);
void ui_event_musiclist(lv_event_t * e);
lv_obj_t * ui_musiclist;
lv_obj_t * ui_Container2;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES


// SCREEN: ui_musicplay
void ui_musicplay_screen_init(void);
void ui_event_musicplay(lv_event_t * e);
lv_obj_t * ui_musicplay;
// CUSTOM VARIABLES


// SCREEN: ui_setting
void ui_setting_screen_init(void);
void ui_event_setting(lv_event_t * e);
lv_obj_t * ui_setting;
lv_obj_t * ui_Container4;
void ui_event_timesetbutton(lv_event_t * e);
lv_obj_t * ui_timesetbutton;
lv_obj_t * ui_Label3;
void ui_event_alarmsetbutton(lv_event_t * e);
lv_obj_t * ui_alarmsetbutton;
lv_obj_t * ui_Label22;
void ui_event_backlightsetbutton(lv_event_t * e);
lv_obj_t * ui_backlightsetbutton;
lv_obj_t * ui_Label4;
// CUSTOM VARIABLES


// SCREEN: ui_timesetting
void ui_timesetting_screen_init(void);
void ui_event_timesetting(lv_event_t * e);
lv_obj_t * ui_timesetting;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container10;
lv_obj_t * ui_hourlabel;
lv_obj_t * ui_Label16;
lv_obj_t * ui_minuteslabel;
lv_obj_t * ui_Label18;
lv_obj_t * ui_secondslabel;
lv_obj_t * ui_Container5;
void ui_event_hour(lv_event_t * e);
lv_obj_t * ui_hour;
lv_obj_t * ui_Label11;
void ui_event_minutes(lv_event_t * e);
lv_obj_t * ui_minutes;
lv_obj_t * ui_Label12;
void ui_event_seconds(lv_event_t * e);
lv_obj_t * ui_seconds;
lv_obj_t * ui_Container9;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label14;
// CUSTOM VARIABLES


// SCREEN: ui_calendar
void ui_calendar_screen_init(void);
void ui_event_calendar(lv_event_t * e);
lv_obj_t * ui_calendar;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label13;
void ui_event_Calendar2(lv_event_t * e);
lv_obj_t * ui_Calendar2;
// CUSTOM VARIABLES


// SCREEN: ui_datesetting
void ui_datesetting_screen_init(void);
void ui_event_datesetting(lv_event_t * e);
lv_obj_t * ui_datesetting;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container12;
lv_obj_t * ui_yearlabel;
lv_obj_t * ui_Label15;
lv_obj_t * ui_monthlabel;
lv_obj_t * ui_Label17;
lv_obj_t * ui_daylabel;
lv_obj_t * ui_Container13;
void ui_event_year(lv_event_t * e);
lv_obj_t * ui_year;
lv_obj_t * ui_Label19;
void ui_event_month(lv_event_t * e);
lv_obj_t * ui_month;
lv_obj_t * ui_Label20;
void ui_event_day(lv_event_t * e);
lv_obj_t * ui_day;
lv_obj_t * ui_Container14;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES


// SCREEN: ui_alarmsetting
void ui_alarmsetting_screen_init(void);
void ui_event_alarmsetting(lv_event_t * e);
lv_obj_t * ui_alarmsetting;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Alarmhourlabel;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Alarmminuteslabel;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Alarmsecondslabel;
lv_obj_t * ui_Container17;
void ui_event_Alarmhour(lv_event_t * e);
lv_obj_t * ui_Alarmhour;
lv_obj_t * ui_Label26;
void ui_event_Alarmminutes(lv_event_t * e);
lv_obj_t * ui_Alarmminutes;
lv_obj_t * ui_Label27;
void ui_event_Alarmseconds(lv_event_t * e);
lv_obj_t * ui_Alarmseconds;
lv_obj_t * ui_Container18;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label28;
// CUSTOM VARIABLES


// SCREEN: ui_alarmScreen
void ui_alarmScreen_screen_init(void);
void ui_event_alarmScreen(lv_event_t * e);
lv_obj_t * ui_alarmScreen;
lv_obj_t * ui_Container19;
lv_obj_t * ui_Label29;
lv_obj_t * ui_alarmContainer;
void ui_event_alarmButton(lv_event_t * e);
lv_obj_t * ui_alarmButton;
lv_obj_t * ui_alarmLabel;
void ui_event_alarmSwitch(lv_event_t * e);
lv_obj_t * ui_alarmSwitch;
lv_obj_t * ui_Container20;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label31;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_ui_bg[2] = {&ui_img_ui_bg2_png, &ui_img_ui_bg3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_menu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        update_call(e);
    }
}

void ui_event_menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_home_screen_init);
    }
}

void ui_event_wifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_wifi_screen_init);
        delet_obj(e);
    }
}

void ui_event_musicButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musiclist, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_musiclist_screen_init);
        delet_obj(e);
    }
}

void ui_event_settingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_calendarButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_calendar, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_calendar_screen_init);
    }
}

void ui_event_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_menu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        wifi_update(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        delet_obj(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifi_connected(e);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wificfg, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_wificfg_screen_init);
        get_ssid(e);
    }
}

void ui_event_homeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
    }
}

void ui_event_wificfg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_wifi_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        wificfg_update(e);
    }
}

void ui_event_musiclist(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_menu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        musiclist_create(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_musicplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_musicplay_screen_init);
        musicplay_create(e);
    }
}

void ui_event_musicplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_musiclist, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_musiclist_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        delet_obj(e);
    }
}

void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_menu_screen_init);
    }
}

void ui_event_timesetbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_timesetting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_timesetting_screen_init);
    }
}

void ui_event_alarmsetbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_alarmScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_alarmScreen_screen_init);
    }
}

void ui_event_backlightsetbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        backlight_change(e);
    }
}

void ui_event_timesetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_setting_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        datetime_setting(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_datesetting, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_datesetting_screen_init);
    }
}

void ui_event_hour(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_minutes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_seconds(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        datetime_update(e);
    }
}

void ui_event_calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_menu_screen_init);
    }
}

void ui_event_Calendar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        calendar_handler(e);
    }
}

void ui_event_datesetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_setting_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        datetime_setting(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_timesetting, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_timesetting_screen_init);
    }
}

void ui_event_year(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_month(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_day(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        datetime_update(e);
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_alarmsetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_alarmScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_alarmScreen_screen_init);
    }
}

void ui_event_Alarmhour(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_Alarmminutes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_Alarmseconds(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        label_update(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarm_update(e);
        _ui_screen_change(&ui_alarmScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 50, &ui_alarmScreen_screen_init);
    }
}

void ui_event_alarmScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_alarmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_alarmsetting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_alarmsetting_screen_init);
    }
}

void ui_event_alarmSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarm_start(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarm_add(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarm_clear(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui_menu_screen_init();
    ui_wifi_screen_init();
    ui_wificfg_screen_init();
    ui_musiclist_screen_init();
    ui_musicplay_screen_init();
    ui_setting_screen_init();
    ui_timesetting_screen_init();
    ui_calendar_screen_init();
    ui_datesetting_screen_init();
    ui_alarmsetting_screen_init();
    ui_alarmScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);
}
