// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "Wireless.h"
#include "freertos/event_groups.h"
#include "lv_examples.h"
#include "LVGL_Example.h"
#include "LVGL_Music.h"
#include <demos/lv_demos.h>

#define LOG

static wifi_ap_record_t new_ap_list[DEFAULT_SCAN_LIST_SIZE];
static wifi_ap_record_t current_ap_list[DEFAULT_SCAN_LIST_SIZE];
static uint16_t current_ap_count = 0;
static lv_obj_t *ui_Button[DEFAULT_SCAN_LIST_SIZE]; // 存储按钮对象
static lv_obj_t *ui_imgButton[DEFAULT_SCAN_LIST_SIZE]; // 存储按钮对象
static lv_timer_t *scan_timer = NULL;
static lv_timer_t *music_timer = NULL;
static wifi_ap_record_t selected_ap;

// static lv_obj_t *kb = NULL;//键盘
static lv_obj_t *ta = NULL;//文本框
static lv_obj_t *close_flag = NULL;
static lv_obj_t *msg_box = NULL;//消息框
static char current_ssid[32] = {0};
EventGroupHandle_t s_wifi_event_group;
static int s_retry_num = 0;
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1
#define WIFI_MAXIMUM_RETRY  5

LV_IMG_DECLARE(ui_img_close_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_pressed_close_png);    // assets/pressed_home.png
//LVGL_Music.c
extern lv_style_t      music_style;
extern const lv_font_t *font_large;
extern lv_obj_t        *spectrum_obj;
extern lv_obj_t        *album_img_obj;
extern lv_obj_t        *panel1;
extern lv_obj_t        *list;
extern uint32_t        track_id;
//main.c
extern QueueHandle_t   step_cnt;
extern QueueHandle_t   bat_queue;
extern QueueHandle_t   time_queue;

lv_obj_t * create_msgbox(const char * title, const char * txt) {
    lv_obj_t * msgbox = lv_msgbox_create(lv_scr_act(), title, txt, NULL, NULL);
    lv_obj_set_style_text_font(lv_msgbox_get_title(msgbox), &ui_font_chinese12, 0);
    lv_obj_set_style_text_font(lv_msgbox_get_text(msgbox), &ui_font_chinese16, 0);
    lv_obj_center(msgbox);
    return msgbox;
}

void wifi_scan_timer(lv_timer_t *timer) 
{
    memset(new_ap_list, 0, sizeof(new_ap_list));

    uint16_t new_ap_count = WIFI_Scan(new_ap_list, DEFAULT_SCAN_LIST_SIZE);

    // 比较新旧AP列表
    bool need_refresh = (new_ap_count != current_ap_count);
    if (!need_refresh) 
    {
        for (int i=0; i<new_ap_count; i++) 
        {
            if (strcmp((char*)new_ap_list[i].ssid, (char*)current_ap_list[i].ssid) != 0) 
            {
                need_refresh = true;
                break;
            }
        }
    }

    // 更新UI
    if (need_refresh) 
    {
        // 删除旧按钮
        for (int i=0; i<current_ap_count; i++) 
        {
            if (ui_Button[i]) lv_obj_del(ui_Button[i]);
        }

        // 创建新按钮
        for (int i=0; i<new_ap_count; i++) 
        {
            // 复制代码中原来的按钮创建逻辑
            ui_Button[i] = lv_btn_create(ui_Container1);
            lv_obj_set_size(ui_Button[i], 360, 50);
            lv_obj_set_y(ui_Button[i], -80 + i*50);
            // ...其他样式设置...
            lv_obj_set_align(ui_Button[i], LV_ALIGN_CENTER);
            lv_obj_add_flag(ui_Button[i], LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
            lv_obj_clear_flag(ui_Button[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
            ui_object_set_themeable_style_property(ui_Button[i], LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                                _ui_theme_color_bgcolor);
            ui_object_set_themeable_style_property(ui_Button[i], LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                                _ui_theme_alpha_bgcolor);
            lv_obj_set_style_border_color(ui_Button[i], lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_Button[i], 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(ui_Button[i], 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(ui_Button[i], LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
            
            lv_obj_t * label = lv_label_create(ui_Button[i]);
            lv_obj_set_width(label, 150);   /// 1
            lv_obj_set_height(label, LV_SIZE_CONTENT);    /// 1
            lv_obj_set_x(label, 80);
            lv_obj_set_y(label, 0);
            lv_obj_set_align(label, LV_ALIGN_LEFT_MID);
            lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL_CIRCULAR);
            // 确保SSID有效且正确复制
            if (strlen((char*)new_ap_list[i].ssid) > 0) 
            {
                lv_label_set_text_fmt(label, "%s", new_ap_list[i].ssid);
            } 
            else 
            {
                lv_label_set_text(label, "Unknown");
            }
            lv_obj_set_style_text_color(label, lv_color_hex(0x00165D), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_opa(label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_letter_space(label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(label, &ui_font_chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);
            
            ui_imgButton[i] = lv_imgbtn_create(ui_Button[i]);
            lv_imgbtn_set_src(ui_imgButton[i], LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rightarrow_png, NULL);
            lv_imgbtn_set_src(ui_imgButton[i], LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_pressed_rightarrow_png, NULL);
            lv_imgbtn_set_src(ui_imgButton[i], LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_pressed_rightarrow_png, NULL);
            lv_obj_set_height(ui_imgButton[i], 50);
            lv_obj_set_width(ui_imgButton[i], 50);   /// 1
            lv_obj_set_x(ui_imgButton[i], -40);
            lv_obj_set_y(ui_imgButton[i], 0);
            lv_obj_set_align(ui_imgButton[i], LV_ALIGN_RIGHT_MID);

            ui_Image1 = lv_img_create(ui_Button[i]);
            lv_img_set_src(ui_Image1, &ui_img_1837598647);
            lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
            lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
            lv_obj_set_x(ui_Image1, 25);
            lv_obj_set_y(ui_Image1, 0);
            lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
            lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
            lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
            // 添加调试日志
            ESP_LOGI("WIFI", "Created button for AP: %s", new_ap_list[i].ssid);
            // 保存AP信息到按钮用户数据
            lv_obj_set_user_data(ui_imgButton[i], (void*)(intptr_t)i);
            lv_obj_set_user_data(ui_Button[i], (void*)(intptr_t)i);
            // 添加事件回调
            lv_obj_add_event_cb(ui_Button[i], ui_event_Button3, LV_EVENT_CLICKED, NULL);
            lv_obj_add_event_cb(ui_imgButton[i], ui_event_ImgButton2, LV_EVENT_CLICKED, NULL);
        }

        // 更新当前AP列表
        memcpy(current_ap_list, new_ap_list, sizeof(current_ap_list));
        current_ap_count = new_ap_count;
    }
}

void event_handler(void* arg, esp_event_base_t event_base,
                                int32_t event_id, void* event_data)
{
    static int i = 0;
    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) 
    {
        esp_wifi_connect();
    } 
    else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) 
    {
        if (s_retry_num < WIFI_MAXIMUM_RETRY) 
        {
            esp_wifi_connect();
            s_retry_num++;
            #ifdef LOG
            ESP_LOGI("wifi_event", "retry to connect to the AP");
            #endif
            if(i==1) s_retry_num = WIFI_MAXIMUM_RETRY;//初始化后的自动连接只执行两次
            i++;
        } 
        else
        {
            xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
        }
        if(strlen(current_ssid))
        {
            #ifdef LOG
            ESP_LOGI("wifi_event", "fail to connect to the AP,%s will be deleted",current_ssid);
            #endif            
            DeleteStoredPassword(current_ssid);
        }
    } 
    else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP && WIFI_EVENT_STA_CONNECTED) 
    {
        ip_event_got_ip_t* event = (ip_event_got_ip_t*) event_data;
        #ifdef LOG
        ESP_LOGI("wifi_event", "got ip:" IPSTR, IP2STR(&event->ip_info.ip));
        #endif
        s_retry_num = 0;
        xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
    }
}

static void show_message(const char * text) 
{
    if(msg_box) lv_obj_del(msg_box);
    msg_box = lv_msgbox_create(lv_scr_act(), "Notification", text, NULL, true);
    #ifdef LOG
    ESP_LOGI("show_message","w");
    #endif
    lv_obj_align(msg_box, LV_ALIGN_CENTER, 0, 0);
}

// 独立任务处理连接
static void connect_wifi_task(void *pvParameters) 
{
    char *ssid = ((struct {char* ssid; char* pass;}*)pvParameters)->ssid;
    char *password = ((struct {char* ssid; char* pass;}*)pvParameters)->pass;
    
    
    wifi_config_t wifi_config = {0};
    if(strlen(ssid))
    {
        strcpy((char*)wifi_config.sta.ssid, ssid);
    }
    if(strlen(password))
    {
        strcpy((char*)wifi_config.sta.password, password);
    }
    
    esp_wifi_disconnect();
    esp_wifi_set_config(WIFI_IF_STA, &wifi_config);
    esp_wifi_connect();
    
    EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group, 
        WIFI_CONNECTED_BIT | WIFI_FAIL_BIT, 
        pdFALSE, pdFALSE, portMAX_DELAY);
    
    // 使用LVGL线程安全API更新UI
    if (bits & WIFI_CONNECTED_BIT) 
    {
        lv_obj_t *label = lv_label_create(lv_scr_act());
        lv_label_set_text(label, "Connected!");
        StorePassword(ssid, password);
    } 
    else 
    {
        lv_obj_t *label = lv_label_create(lv_scr_act());
        #ifdef LOG
        ESP_LOGI("wifi_event","connect to the AP fail");
        #endif
        lv_label_set_text(label, "Failed!");
        DeleteStoredPassword(ssid);
    }
    
    free(ssid);
    free(password);
    vTaskDelete(NULL);
}

// 在ConnectToWiFi中启动任务
void ConnectToWiFi(const char* ssid, const char* password) 
{
    char *task_ssid = strdup(ssid);
    char *task_password = strdup(password);
         
    xTaskCreatePinnedToCore(
        connect_wifi_task,   // 任务函数
        "wifi_connect_task", 
        4096, 
        (void*)&(struct {char* ssid; char* pass;}){task_ssid, task_password},
        2,  // 优先级高于LVGL任务
        NULL, 
        0
    );
}

static void keyboard_event_cb(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * kb = lv_event_get_target(e);
    lv_obj_t * ta = lv_event_get_user_data(e);
    
    if (code == LV_EVENT_READY) {
        if (ta) {
            const char * password = lv_textarea_get_text(ta);
            // 仅传递密码，不在此处存储
            ConnectToWiFi(current_ssid, password);
        }
        
        // 清理UI组件
        if (ta) lv_obj_del(ta);
        if (kb) lv_obj_del(kb);
        
        // 重启扫描定时器
        if (scan_timer) lv_timer_del(scan_timer);
        scan_timer = lv_timer_create(wifi_scan_timer, 10000, NULL);
    }
}

// static void switch_keyboard_mode(lv_event_t * e) 
// {
//     static bool num_mode = false;
//     lv_keyboard_set_mode(kb, num_mode ? LV_KEYBOARD_MODE_TEXT_LOWER : LV_KEYBOARD_MODE_NUMBER);
//     num_mode = !num_mode;
// }

// static void show_keyboard() 
// {
//     // 创建文本框
//     ta = lv_textarea_create(lv_scr_act());
//     lv_obj_set_size(ta, 200, 80);
//     lv_obj_align(ta, LV_ALIGN_TOP_MID, 0, 40);
//     lv_textarea_set_placeholder_text(ta, "Enter password");
//     lv_textarea_set_password_mode(ta, true);
//     lv_textarea_set_one_line(ta, true);

//     // 创建键盘
//     kb = lv_keyboard_create(lv_scr_act());
//     lv_keyboard_set_textarea(kb, ta);
//     lv_obj_add_event_cb(kb, keyboard_event_cb, LV_EVENT_ALL, NULL);
//     lv_obj_set_size(kb, 320, 160);
//     lv_obj_align(kb, LV_ALIGN_BOTTOM_MID, 0, -50);

//     // 添加切换按钮
//     lv_obj_t *sw_btn = lv_btn_create(lv_scr_act());
//     lv_obj_set_size(sw_btn, 80, 40);
//     lv_obj_align(sw_btn, LV_ALIGN_CENTER, 0, -30);
//     lv_obj_t *label = lv_label_create(sw_btn);
//     lv_label_set_text(label, "123/ABC");
//     lv_obj_add_event_cb(sw_btn, switch_keyboard_mode, LV_EVENT_CLICKED, NULL);
// }

#if LV_USE_KEYBOARD && LV_BUILD_EXAMPLES

static void ta_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    lv_obj_t * kb = lv_event_get_user_data(e);
    if(code == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(kb, ta);
        lv_obj_clear_flag(kb, LV_OBJ_FLAG_HIDDEN);
    }

    if(code == LV_EVENT_DEFOCUSED) {
        lv_keyboard_set_textarea(kb, NULL);
        lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
    }
}

static void close_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * kb = lv_event_get_user_data(e);
    if(code == LV_EVENT_CLICKED)
    {
        if (ta) lv_obj_del(ta);
        if (kb) lv_obj_del(kb);
        if (close_flag) lv_obj_del(close_flag);
    }
}
void lv_example_keyboard_1(void)
{
    /*Create a keyboard to use it with an of the text areas*/
    lv_obj_t * kb = lv_keyboard_create(lv_scr_act());
    lv_obj_align(kb, LV_ALIGN_CENTER, 0, 10);
    lv_obj_set_style_bg_opa(kb,200,LV_PART_MAIN);
    /*Create a text area. The keyboard will write here*/

    ta = lv_textarea_create(lv_scr_act());
    lv_obj_align(ta, LV_ALIGN_TOP_MID, -20, 50);
    lv_obj_add_event_cb(ta, ta_event_cb, LV_EVENT_ALL, kb);
    lv_textarea_set_placeholder_text(ta, "Hello");
    lv_obj_set_size(ta, 200, 40);

    close_flag = lv_imgbtn_create(lv_scr_act());
    lv_imgbtn_set_src(close_flag, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_close_png, NULL);
    lv_imgbtn_set_src(close_flag, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_pressed_close_png, NULL);
    lv_obj_set_height(close_flag, 49);
    lv_obj_set_width(close_flag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(close_flag, 97);
    lv_obj_set_y(close_flag, 45);
    lv_obj_set_align(close_flag, LV_ALIGN_TOP_MID);
    lv_obj_add_event_cb(close_flag, close_event_cb, LV_EVENT_ALL, kb);

    lv_obj_add_event_cb(kb, keyboard_event_cb, LV_EVENT_ALL, ta);
    lv_keyboard_set_textarea(kb, ta);
}
#endif

//用于按下wifi按钮时，连接wifi
void wifi_connected(lv_event_t * e) {
    // 获取当前选择的SSID
    if(scan_timer) 
	{
		lv_timer_del(scan_timer);
		scan_timer = NULL;
	}
    lv_obj_t * btn = lv_event_get_target(e);
    int index = (int)(intptr_t)lv_obj_get_user_data(btn);
    strncpy(current_ssid, (char *)new_ap_list[index].ssid, sizeof(current_ssid));
    // 检查是否有存储密码
    char password[64] = {0};
    if(GetStoredPassword(current_ssid, password, sizeof(password))) 
    {
        #ifdef LOG
         ESP_LOGI("pass","pass:%s",password);
        #endif
        // show_message("Connecting to stored network...");
        ConnectToWiFi(current_ssid, password);
        
    } else {
        lv_example_keyboard_1();
    }
}



//用于显示wifi详情页的参数
void wificfg_update(lv_event_t * e)
{
	char info[512];
	snprintf(info, sizeof(info),
		"   SSID:           %s\n"
		"   RSSI:           %d\n"
		"   Auth:           %d\n"
		"   Channel:      %d",
		selected_ap.ssid,
		selected_ap.rssi,
		selected_ap.authmode,
		selected_ap.primary
	);
	lv_label_set_text(ui_Label8, info);
}
//用于加载wifi页面时扫描wifi
void wifi_update(lv_event_t * e)
{

	scan_timer = lv_timer_create(wifi_scan_timer, 8000, NULL); // 10秒扫描一次

}
//用于按下wifi详情按钮时获取相应的wifi信息
void get_ssid(lv_event_t * e)
{
	// 获取AP信息
	int wifi_index = (int)(intptr_t)lv_obj_get_user_data(lv_event_get_target(e));
	
	// 传递到wificfg页面（假设有全局变量）
	
	memcpy(&selected_ap, &new_ap_list[wifi_index], sizeof(wifi_ap_record_t));
    #ifdef LOG
    ESP_LOGI("WIFICFG", "更新网络信息: %s", selected_ap.ssid);
    #endif
	_ui_screen_change(&ui_wificfg, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_wificfg_screen_init);
}

void delet_obj(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
	if(ui_Button3) 
	{
		lv_obj_del(ui_Button3);
		ui_Button3 = NULL;
	}
    if(ui_Button1)
    {
        lv_obj_del(ui_Button1);
		ui_Button1 = NULL;
    }
    // if(panel1&&(obj==ui_musicplay)) 
    // {
    //     lv_obj_del(panel1);
    //     panel1 = NULL;
    // }
    // 清理列表相关资源
    if(list&&(obj==ui_musicplay)) 
    {
        lv_obj_del(list);
        list = NULL;
    }
    if(scan_timer) 
	{
		lv_timer_del(scan_timer);
		scan_timer = NULL;
	}
    if(music_timer&&(obj==ui_musicplay)) 
	{
		lv_timer_del(music_timer);
		music_timer = NULL;
	}
    if(ui_musiclist&&(obj==ui_musicplay)) 
    {
        lv_event_send(ui_musiclist, LV_EVENT_REFRESH, NULL);
    }
    if(obj==ui_musicplay)
    {
        _lv_demo_music_pause();
    }
    
}
void musiclist_create(lv_event_t * e)
{
	// Your code here
    // lv_obj_clean(ui_Container2);
    LVGL_Search_Music();   
    if(ACTIVE_TRACK_CNT) 
    {                           
        panel1 = lv_obj_create(ui_musicplay);
        lv_obj_set_height(panel1, LV_SIZE_CONTENT);
        lv_obj_t * list_box = create_List_box(ui_Container2);
        
        lv_obj_set_size(list_box, LV_SIZE_CONTENT, LV_SIZE_CONTENT);               

        // 列定义：单列铺满
        static lv_coord_t grid_col_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};

        // 行定义保持不变
        static lv_coord_t grid_row_dsc[] = {
            LV_GRID_CONTENT, 
            LV_GRID_TEMPLATE_LAST   
        };
        lv_obj_set_grid_dsc_array(ui_Container2, grid_col_dsc, grid_row_dsc); 
        // list_box 占用单列，水平拉伸
        lv_obj_set_grid_cell(
            list_box, 
            LV_GRID_ALIGN_STRETCH,  // 水平拉伸
            0, 1,                   // 从第0列开始，占用1列
            LV_GRID_ALIGN_CENTER,   // 垂直居中
            0, 1                    // 从第0行开始，占用1行
        );    
    }
    else{ 
        lv_obj_t *label = lv_label_create(ui_Container2);
        lv_label_set_text(label, "No MP3 file found in SD card!");

        lv_obj_set_size(label, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
        lv_obj_align(label, LV_ALIGN_CENTER, 0, 0);
        lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, 0);  
    }
}

void musicplay_create(lv_event_t * e)
{
	// Your code here                          
    lv_style_init(&music_style);
    lv_style_set_text_font(&music_style, font_large);

    // lv_obj_t * cont = create_cont(panel1);
    // create_wave_images(cont);
    spectrum_obj = create_spectrum_obj(panel1);
    lv_obj_add_style(spectrum_obj, &music_style, 0);


    lv_obj_t * title_box = create_title_box(panel1);
    lv_obj_add_style(title_box, &music_style, 0);
    lv_obj_t * ctrl_box = create_ctrl_box(panel1);
    lv_obj_add_style(ctrl_box, &music_style, 0);
  
    static lv_coord_t grid_main_col_dsc[] = {LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t grid_main_row_dsc[] = {LV_GRID_CONTENT, LV_GRID_TEMPLATE_LAST};
    lv_obj_set_grid_dsc_array(ui_musicplay, grid_main_col_dsc, grid_main_row_dsc);
    lv_obj_set_grid_cell(panel1, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_START, 0, 1);
  /*Create the top panel*/
    static lv_coord_t grid_1_col_dsc[] = {LV_GRID_CONTENT, LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static lv_coord_t grid_1_row_dsc[] = {
      LV_GRID_CONTENT,      /*title_box*/
      LV_GRID_CONTENT,      /*cont*/
      170,                   /*spectrum_obj*/
      LV_GRID_CONTENT,      /*ctrl_box*/
      LV_GRID_TEMPLATE_LAST
      };
    lv_obj_set_grid_dsc_array(panel1, grid_1_col_dsc, grid_1_row_dsc);        
    lv_obj_set_grid_cell(title_box    , LV_GRID_ALIGN_STRETCH, 0, 2, LV_GRID_ALIGN_CENTER, 0, 1);
    // lv_obj_set_grid_cell(cont         , LV_GRID_ALIGN_STRETCH, 1, 1, LV_GRID_ALIGN_CENTER, 1, 1);
    lv_obj_set_grid_cell(spectrum_obj , LV_GRID_ALIGN_STRETCH, 0, 2, LV_GRID_ALIGN_CENTER, 2, 1);
    lv_obj_set_grid_cell(ctrl_box , LV_GRID_ALIGN_STRETCH, 0, 2, LV_GRID_ALIGN_CENTER, 3, 1);

    music_timer = lv_timer_create(timer_cb, 100, NULL);


    lv_obj_fade_in(title_box, 500, INTRO_TIME - 1000);
    lv_obj_fade_in(ctrl_box, 500, INTRO_TIME - 1000);
    lv_obj_fade_in(album_img_obj, 300, INTRO_TIME - 1000);
    lv_obj_fade_in(spectrum_obj, 0, INTRO_TIME - 1000);
}

//home设计
void update_timer(lv_timer_t * timer)
{
    // lv_obj_t * arc = (lv_obj_t *)timer->user_data;
    // lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(arc);
    static int i = 0;
    // 获取当前步数
    uint32_t steps;
    if(xQueueReceive(step_cnt,&steps,0)==pdPASS)
    {    
        // 更新弧形进度（假设目标10000步）
        lv_arc_set_value(ui_stepArc, steps % 10000);
        
        // 更新文本
        lv_label_set_text_fmt(ui_steplabel, "%ld", steps);
        
        // 动态颜色变化
        lv_color_t color = steps > 5000 ? lv_color_hex(0xFF0000) : lv_color_hex(0x00FF00);
        lv_obj_set_style_arc_color(ui_stepArc, color, LV_PART_INDICATOR);
    }
    datetime_t time;
    if (xQueueReceive(time_queue,&time,0))
    {
        lv_label_set_text_fmt(ui_Labeltime, "%d:%d", time.hour,time.minute);
        lv_label_set_text_fmt(ui_Label5, "%d年%d月%d日", time.year,time.month,time.day); 
    }
    
    float bat_volts;
    if (xQueueReceive(bat_queue,&bat_volts,0)==pdPASS)
    {
        lv_label_set_text_fmt(ui_batlabel, "%d%%", (int)bat_volts);
        lv_arc_set_value(ui_batArc, (int)bat_volts);
    }
}

void update_call(lv_event_t * e)
{
	// Your code here
    static lv_timer_t * step_timer = NULL;
    step_timer = lv_timer_create(update_timer,20, NULL);
}

void backlight_change(lv_event_t * e)
{
	// Your code here
}


void datetime_setting(lv_event_t * e)
{
	// Your code here
}

static void set_label(lv_obj_t *roller,lv_obj_t *label)
{
    char buf[32];
    lv_roller_get_selected_str(roller, buf, sizeof(buf));
    lv_label_set_text(label,buf);
}

void label_update(lv_event_t * e)
{
	lv_obj_t *roller[9] = {ui_hour,ui_minutes,ui_seconds,
                           ui_year,ui_month,ui_day,
                           ui_Alarmhour,ui_Alarmminutes,ui_Alarmseconds,};
    lv_obj_t *label[9]  = {ui_hourlabel,ui_minuteslabel,ui_secondslabel,
                           ui_yearlabel,ui_monthlabel,ui_daylabel,
                           ui_Alarmhourlabel,ui_Alarmminuteslabel,ui_Alarmsecondslabel,};
    for (size_t i = 0; i < 9; i++)
    {
        set_label(roller[i],label[i]);
    }
}

static int getdays(int year,int month) 
{
    int daysInMonth[] = {
        0, 31, 28, 31, 30, 31, 30, 
        31, 31, 30, 31, 30, 31
    };
    if (month == 2 && ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0))) 
    {
        daysInMonth[2] += 1;
    }
    return daysInMonth[month];
}

void datetime_update(lv_event_t * e)
{
	//先判断是哪个屏幕被按下了确认键
    lv_obj_t *obj = lv_event_get_target(e);
    datetime_t time;
    if (obj==ui_Button2)
    {  
        time.hour   = (uint8_t)atoi(lv_label_get_text(ui_hourlabel));
        time.minute = (uint8_t)atoi(lv_label_get_text(ui_minuteslabel));
        time.second = (uint8_t)atoi(lv_label_get_text(ui_secondslabel));
        
        PCF85063_Set_Time(time);
    }
    else
    {
        
        time.year   = (uint16_t)atoi(lv_label_get_text(ui_yearlabel));
        time.month  = (uint8_t)atoi(lv_label_get_text(ui_monthlabel));
        time.day    = (uint8_t)atoi(lv_label_get_text(ui_daylabel));
        #ifdef LOG
        ESP_LOGI("datetime_update","time.year:%d",time.year);
        ESP_LOGI("datetime_update","time.month:%d",time.month);
        ESP_LOGI("datetime_update","time.day:%d",time.day);
        #endif
        
        if (time.day > getdays(time.year,time.month))
        {
            char tmp[128];
            sprintf(tmp,"current day can't over %d.",getdays(time.year,time.month));
            lv_obj_t *err_msg = lv_msgbox_create(NULL,"error!!!",tmp,NULL,true);
            lv_obj_center(err_msg);
        }
        else
        {
            PCF85063_Set_Date(time);
        }
               
    }
    
}


void calendar_handler(lv_event_t * e)
{
	// Your code here
}

static struct
{
    int num;
    lv_obj_t *alarmButton[128];
    lv_obj_t *alarmLabel[128];
    lv_obj_t *alarmSwitch[128];
}alarm_btn;

void Alarm(int index) 
{
    alarm_btn.alarmButton[index] = lv_btn_create(ui_alarmContainer);
    lv_obj_t *alarmButton = alarm_btn.alarmButton[index];
    alarm_btn.alarmLabel[index] = lv_label_create(alarmButton);
    lv_obj_t *alarmLabel = alarm_btn.alarmLabel[index];
    alarm_btn.alarmSwitch[index] = lv_switch_create(alarmButton);
    lv_obj_t *alarmSwitch = alarm_btn.alarmSwitch[index];

    lv_obj_set_width(alarmButton, 360);
    lv_obj_set_height(alarmButton, 50);
    lv_obj_set_align(alarmButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(alarmButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(alarmButton, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(alarmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(alarmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(alarmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(alarmButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(alarmButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(alarmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(alarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(alarmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(alarmLabel, "00:00:00");
    lv_obj_set_style_text_color(alarmLabel, lv_color_hex(0x070606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(alarmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(alarmLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(alarmSwitch, 75);
    lv_obj_set_height(alarmSwitch, 40);
    lv_obj_set_align(alarmSwitch, LV_ALIGN_CENTER);

    static int num = 0;
    lv_obj_add_event_cb(alarmButton, ui_event_alarmButton, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(alarmButton, alarm_update, LV_EVENT_CLICKED, num);
    lv_obj_add_event_cb(alarmSwitch, alarm_start, LV_EVENT_CLICKED, num++);
}

void alarm_start(lv_event_t * e)
{
    int num = lv_event_get_user_data(e);
    datetime_t* alarm = (datetime_t*)lv_obj_get_user_data(alarm_btn.alarmLabel[num]);
    #ifdef LOG
    ESP_LOGI("alarm_start","alarm.hour:%d",alarm->hour);
    ESP_LOGI("alarm_start","alarm.minute:%d",alarm->minute);
    ESP_LOGI("alarm_start","alarm.second:%d",alarm->second);
    #endif
    PCF85063_Set_Alarm(*alarm);
}

void alarm_add(lv_event_t * e)
{
	Alarm(alarm_btn.num++);
    if (alarm_btn.num>128)
    {
        create_msgbox("错误","闹钟数量已达上限 (128)!");
    }
    #ifdef LOG
    ESP_LOGI("alarm_add","成功添加%d个",alarm_btn.num);
    #endif
}

void alarm_clear(lv_event_t * e)
{
    if (alarm_btn.num <= 0)
    {
        create_msgbox("错误","没有闹钟可删除!");
        return;
    }
    if (alarm_btn.alarmButton[--alarm_btn.num] != NULL)
    {
        // 释放关联的 datetime_t 内存
        datetime_t *alarm = (datetime_t *)lv_obj_get_user_data(alarm_btn.alarmLabel[alarm_btn.num]);
        if (alarm != NULL) free(alarm);
        lv_obj_del(alarm_btn.alarmButton[alarm_btn.num]);
        alarm_btn.alarmButton[alarm_btn.num] = NULL;
    }
    #ifdef LOG
    ESP_LOGI("alarm_del","剩余%d个",alarm_btn.num);
    #endif
}

void alarm_update(lv_event_t * e)
{
    lv_obj_t *obj = lv_event_get_target(e);
    static int num;
    if(obj != ui_Button5) num = lv_event_get_user_data(e);
    else
    {
        char tmp[128];
        datetime_t *alarm = (datetime_t *)malloc(sizeof(datetime_t));
        alarm->hour = (uint8_t)atoi(lv_label_get_text(ui_Alarmhourlabel));
        alarm->minute = (uint8_t)atoi(lv_label_get_text(ui_Alarmminuteslabel));
        alarm->second = (uint8_t)atoi(lv_label_get_text(ui_Alarmsecondslabel));
        sprintf(tmp,"%d:%d:%d",alarm->hour,alarm->minute,alarm->second);
        if (alarm_btn.alarmLabel[num]!=NULL)
        {
            lv_obj_set_user_data(alarm_btn.alarmLabel[num],alarm);
            lv_label_set_text(alarm_btn.alarmLabel[num],tmp);
        }
    }
}
